# --- !Ups

create table "EVENT" ("ID" BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(120) NOT NULL,
  "DESCRIPTION" VARCHAR,
  "EVENT_CATEGORY" VARCHAR(60) NOT NULL,
  "START_DATE_TIME" DATETIME NOT NULL,
  "END_DATE_TIME" DATETIME);

# --- !Downs
drop table "EVENT";