# --- !Ups

create table "EVENT" ("ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(120) NOT NULL,
  "DESCRIPTION" VARCHAR NOT NULL,
  "EVENT_CATEGORY" VARCHAR(60) NOT NULL,
  "START_DATE_TIME" BIGINT NOT NULL,
  "END_DATE_TIME" BIGINT);

-- insert into EVENT ("NAME", "DESCRIPTION", "EVENT_CATEGORY", "START_DATE_TIME", "END_DATE_TIME")
--   VALUES ('Damian', 'lolasldasod', 'Workshops', 1497375479, 1497375479);

# --- !Downs
drop table "EVENT";